### ISSUE TITLE
Scrobbling long track+album+artist to last.fm fails with "Invalid method signature"

### ISSUE THREAD

**Issue by ChandlerSwift** [mariusor/mpris-scrobbler#101]
`MAX_PROPERTY_LENGTH` is defined to be 384:

https://github.com/mariusor/mpris-scrobbler/blob/0d42d4ff9fab38ecf63a1d08d4a447f1c04b639b/src/structs.h#L43

This comes into play when we generate the signature for the request[^process]:

[^process]: Because I had to look it up: the signature process is documented at https://www.last.fm/api/webauth#_6-sign-your-calls

https://github.com/mariusor/mpris-scrobbler/blob/0d42d4ff9fab38ecf63a1d08d4a447f1c04b639b/src/audioscrobbler_api.h#L256-L277

Specifically, the `string` argument passed to this function is a string of the format `album{album}api_key{api_key,32char}artist{artist}methodtrack.updateNowPlayingsk{sk,32char}track{track}`. Every value but those for `album`, `artist`, and `track` are constant-length, and total 117 characters.

Line 267 truncates the string if it ever exceeds `MAX_PROPERTY_LENGTH/2 == 192` characters:
https://github.com/mariusor/mpris-scrobbler/blob/0d42d4ff9fab38ecf63a1d08d4a447f1c04b639b/src/audioscrobbler_api.h#L267

Then the signature is created based on the truncated string, but the full-length string is submitted to last.fm, which leads to the titular signature mismatch.

There are at least a handful of songs in my library that do this. The one I was using for debugging was [this one](https://musicbrainz.org/recording/58afea74-e6ca-4448-a22f-00f0a0d32f43): "When the Time Has Come" (22 characters) by Huey Lewis & the News (21 characters) off the album "Time Flies… The Best of Huey Lewis & the News" (47 characters). With the 117 constant characters, above, we have a `string` of length `117+22+21+47 == 207`, well exceeding the max size of 192 characters.

As a kludge to help fix this, I doubled `MAX_PROPERTY_LENGTH`. This fixes all the songs I tested. That said, there may be album/artist/track combinations that are long enough to still cause issues even with a higher limit[^absurd] -- would it make sense for this to be dynamically allocated?

[^absurd]: And they can really get absurd! e.g. a few from https://web.archive.org/web/20241002044440/https://dustri.org/b/horrible-edge-cases-to-consider-when-dealing-with-music.html

I'm not a particularly good C programmer, but I'd be happy to put together an attempt at dynamic allocation for the buffer in that particular function, and maybe try to add some test cases to make sure things work with a reasonable length of album/artist/track, if you'd like!

Here's the specific error I was seeing in the logs (when run with some number of `v`'s, also compiled in debug mode, I think?)
```text
TRACING curl::transfer::done[0]: https://ws.audioscrobbler.com/2.0/?format=json in check_multi_info() src/curl.h:82
TRACING   response::status: 400 
TRACING     response(0x194e80b0:58): {"message":"Invalid method signature supplied","error":13}
TRACING     response::headers[0]: server: openresty/1.13.6.2
TRACING     response::headers[1]: date: Sat, 05 Oct 2024 04:47:20 GMT
TRACING     response::headers[2]: content-type: application/json
TRACING     response::headers[3]: content-length: 58
TRACING     response::headers[4]: access-control-allow-methods: POST, GET, OPTIONS
TRACING     response::headers[5]: access-control-allow-origin: *
TRACING     response::headers[6]: access-control-max-age: 86400
TRACING     response::headers[7]: via: 1.1 google
TRACING     response::headers[8]: alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
INFO     api::submitted_to[last.fm]: nok
```

**Comment by mariusor** [comment]
Hi @ChandlerSwift, sorry for the long time it took me to notice this, I don't really keep an eye on the Github issues because I am hoping people will interact with the [mailing list](https://github.com/mariusor/mpris-scrobbler?tab=readme-ov-file#resources) instead.

Yeah, this is a serious oversight. The signature string needs to be quite large based on the amount of information it can hold.

I changed it to 16k and added some assertions in the function that builds that string for the cases where it exceeds even that.

I'd appreciate it if you could test the debug version of the scrobbler for a while and let me know if you hit any of them.

**Comment by ChandlerSwift** [comment]
LGTM!

Before:
```console
[chandler@oscar:~/projects/nixpkgs/pkgs/by-name/mp/mpris-scrobbler]$ mpris-scrobbler --help | grep version
MPRIS scrobbler daemon, version 0.5.3

[chandler@oscar:~/projects/nixpkgs/pkgs/by-name/mp/mpris-scrobbler]$ mpris-scrobbler -vvv
DEBUG   main::loading_config: ok
DEBUG   main::loading_credentials: ok
DEBUG   events::add_event:now_playing[Elisa] in 0.00s, elapsed 72.82s
DEBUG   events::add_event:queue[Elisa] in 61.00s
INFO    scrobbler::now_playing[Elisa]: When the Time Has Come//Huey Lewis and the News//Time Flies… The Best of Huey Lewis & the News
DEBUG   events::add_event:now_playing[Elisa] in 65.00s, elapsed 72.82s
INFO     api::submitted_to[last.fm]: nok
^CINFO    main::signal_received: SIGINT
```
After:
```console
[chandler@oscar:~/]$ mpris-scrobbler-0.5.5 --help | grep version
MPRIS scrobbler daemon, version 0.5.5

[chandler@oscar:~/]$ mpris-scrobbler-0.5.5 -vvv
DEBUG   main::loading_config: ok
DEBUG   main::loading_credentials: ok
DEBUG   events::add_event:now_playing[Elisa] in 0.00s, elapsed 216.82s
DEBUG   events::add_event:queue[Elisa] in 0.00s
INFO    scrobbler::now_playing[Elisa]: When the Time Has Come//Huey Lewis and the News//Time Flies… The Best of Huey Lewis & the News
INFO    scrobbler::scrobble:(   0) When the Time Has Come//Huey Lewis and the News//Time Flies… The Best of Huey Lewis & the News
DEBUG   events::new_queue_length: 0
INFO     api::submitted_to[last.fm]: ok
INFO     api::submitted_to[last.fm]: ok
^CINFO    main::signal_received: SIGINT
```

Thanks for the fix!

**Comment by mariusor** [comment]
Wonderful. 

Truth be told I did get random last.fm failures in my submissions after one version where I tried to fix a lot of `-Wpedantic` warnings about various stringop issues. 

I never put the two together, that in the process I managed to truncate the buffer for the hash. So thank you, again.
