### ISSUE TITLE
Support for custom ListenBrainz servers

### ISSUE THREAD

**Issue by LeoVerto** [mariusor/mpris-scrobbler#33]
I'd love to be able to set up mpris-scrobbler to send listens to my local dev ListenBrainz server without having to touch the hosts file.

**Comment by mariusor** [comment]
Try adding a `url = <url>` to the listenbrainz credentials file. It should work already, but I don't think I've tested the feature.

**Comment by mariusor** [comment]
Confirmed on IRC that "it works" with the caveat in #36. 

Closing.
