### ISSUE TITLE
Don't append CURL requests if one is already in the queue for the current API

### ISSUE THREAD

**Issue by mariusor** [mariusor/mpris-scrobbler#46]
Sometimes the queue of API requests shows more than one call for a service, which shouldn't be done:

    INFO    scrobbler::now_playing: Variationen zur Gesundung von Arinuschka//Jeroen van Veen//Minimal Piano Works, Volume II
    INFO     api::submitted_to[listenbrainz.org]: ok
    INFO     api::submitted_to[last.fm]: ok
    INFO     api::submitted_to[libre.fm]: ok
    INFO     api::submitted_to[libre.fm]: ok
    INFO     api::submitted_to[last.fm]: ok
    INFO     api::submitted_to[libre.fm]: ok

We should detect if a call is already in the queue for a service and replace it, or do not add it all together. 

But I don't know what's the underlying problem that's triggering this issue.

**Comment by jwflory** [comment]
Would this be related to a song being scrobbled twice at the same time, e.g. starting a song and immediately skipping to the next scrobbles both of the songs?

**Comment by mariusor** [comment]
No, I don't think so. I suspect there's some async issue when adding the event. My plan is to check that a request doesn't exist in the current batch before adding it.

Also what you mention theoretically shouldn't happen as one of the rules for a valid scrobble require that a song has played for 4 minutes or half of its length. Some players that don't report song length or play time correctly might show weird results.

**Comment by jwflory** [comment]
@mariusor Interesting. I guess this is a different bug. Sometimes I noticed I would have double scrobbles even if a song is played momentarily. I was trying out the [cmus music player](https://cmus.github.io/).

**Comment by mariusor** [comment]
Could you please open a separate ticket for that so I will remember later to take a look?

I'm sure my code regarding a scrobble being valid or not could use some improvements, and this would be just the thing to put things in motion.
