### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Bergiu** [mariusor/mpris-scrobbler#48]
Problem:
The service loads a different file than the command mpris-scrobble-signon creates.

How to reproduce:
1. Installed the program like described in the README.md
2. Started mpris-scrobbler.service
    -  `systemctl --user start mpris-scrobbler.service`
    - In the `journalctl --user -u mpris-scrobbler-service` there ist this log:
        - `WARNING main::loading_credentials: failed`
        - `WARNING main::load_credentials: no credentials were loaded`
3. Enable librefm
    - `mpris-scrobbler-signon enable librefm`
    - This creates the file `~/.config/mpris-scrobbler/credentials` with librefm `enabled = true`
4. Created a token and session:
    - `mpris-scrobbler-signon token librefm`
    - `mpris-scrobbler-signon session librefm`
    - During that, the file `~/.config/mpris-scrobbler/credentials` is filled with a token, a username and a session.
5. Now I restart the service `systemctl --user restart mpris-scrobbler.service` and get the same warning:
    - `WARNING main::loading_credentials: failed`
    - `WARNING main::load_credentials: no credentials were loaded`

To solve the problem, after that I have copied the credentials file to another location:
- `cp ~/.config/mpris-scrobbler/credentials ~/.local/share/mpris-scrobbler/credentials`

Then restart the service again.

Same problem on lastfm.

**Comment by mariusor** [comment]
Thank you for submitting this. 

Seems like I didn't update the saving of the credentials file to the proper path. 

I'll fix it as soon as possible.

**Comment by mariusor** [comment]
So, as an update: 

I'm testing on git master and the credentials file is created in the proper place, in ~/.local/share/mpris-scrobbler.

It's possible that the problem is triggered by something local to your machine. Can you tell me which distribution and which version of mpris-scrobbler are you running? 

And can you please paste here the output of this command? 

    $ env | grep XDG | grep -Evi 'path|desk'

**Comment by mariusor** [comment]
Thanx, I'll give it a try with a similar environment configuration.

I suspect that the main issue is that you're missing `XDG_DATA_HOME` in your environment when you run the signon helper. I'll try to improve the logic of generating this path in less standard configurations.

Do you have the HOME env var set? (`$ env  | grep HOME`)

**Comment by mariusor** [comment]
Ok, thank you. This should be enough for me to reproduce. Can't promise a date by when I can do this, but I'll ping you once I have something.

**Comment by Bergiu** [comment]
I will test later if it works when I set the XDG_DATA_HOME dir.

**Comment by Bergiu** [comment]
Setting `XDG_DATA_HOME=~/.local/share` fixed this problem. It seems that I've forgot to set this in my system settings.

**Comment by Bergiu** [comment]
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html:
"If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used."

**Comment by mariusor** [comment]
Yes, this is what I'm already doing see: https://github.com/mariusor/mpris-scrobbler/blob/37f1e60a69abc6b8a315938dc1c25ac51c309146/src/configuration.h#L253

Probably the logic is broken somehow. I'll fix it.
