### ISSUE TITLE
Occasional double-scrobbles / pre-mature scrobbles submitted to scrobble server

### ISSUE THREAD

**Issue by jwflory** [mariusor/mpris-scrobbler#50]
# Summary

Occasionally a song is either:

1. Double-scrobbled to a scrobble server, or
2. Mistakenly scrobbled when played for a few seconds

# Background

I noticed a few times when using mpris-scrobbler, a bad scrobble made it through (as described above). A few things of note:

* Bad scrobble makes it to _all_ scrobble servers (Last.fm, Libre.fm, ListenBrainz)
* Seems to be independent of player, but I am using [cmus](https://cmus.github.io/) and the Spotify client

# Details

Not sure what a fix would entail for this. The issue is sporadic and hard to narrow down what triggers it. Sometimes I only notice it long after a play.

# Outcome

Better data accuracy of scrobbled songs :tada:

**Comment by mariusor** [comment]
Hi @jwflory, I released a new version that has some improvements to the logic of scrobble validation. 

Please give it a try and add some more info to the ticket if it still happens for you. (A minimal reproducible case would be great - which songs and which player)

**Comment by jwflory** [comment]
Hi @mariusor, I packaged 0.3.2 this morning for Fedora/CentOS/RHEL. More info is in [this Bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1697112). I should have more feedback for you soon. Give me a few days to test it. :slightly_smiling_face:

**Comment by mariusor** [comment]
This ticket depends on #55 and on #46.

**Comment by treeshateorcs** [comment]
double scrobbles on listenbrainz (lastfm is not affected
![image](https://user-images.githubusercontent.com/44036082/64073968-e1ba4400-ccad-11e9-8b3c-b1f232d0e550.png)


an excerpt from the logs https://pastebin.com/iT2CGfXz

**Comment by mariusor** [comment]
Hi again @treeshateorcs, which media player is this?

**Comment by treeshateorcs** [comment]
ah, sorry, forgot to mention it.

I'm using mopidy with mopidy-spotify and mopidy-mpris plugins

**Comment by jwflory** [comment]
For what it is worth, I have not noticed double-scrobbling lately. But now that I am running v0.3.91, I will watch more closely for a week or so if I notice any double-scrobbles

**Comment by mariusor** [comment]
I'll look into it some more, on my side, I've been using this release for about 2 weeks and I had no double scrobbles, even in the same configuration: Spotify and listenbrainz.

**Comment by mariusor** [comment]
I think I'm going to close this issue.

**Comment by jwflory** [comment]
Works for me too :smile: I've been using it since May and haven't noticed any double-scrobbles. Thanks for working on this and getting it fixed! :tada:
