### ISSUE TITLE
Allow pull request for Ubuntu 18.04 documentation

### ISSUE THREAD

**Issue by alecvn** [mariusor/mpris-scrobbler#52]
Hi

Thanks for your work on this scrobbler!

I've installed and got `mpris-scrobbler` working on two different systems running Ubuntu 18.04 and subsequently compiled a section for it in the `README`.  I felt it was just different and tricky enough to require its own set of instructions.

If you would allow me to make a pull request I will send it through.

**Comment by mariusor** [comment]
Of course, please do. Any contribution is welcome.

**Comment by alecvn** [comment]
I don't seem to currently be able to.

**Comment by mariusor** [comment]
I'm not sure what you're trying to do, but forking the repository, pushing the changes to your own repo, and then opening a pull request against mine will do the trick.

There's an [article](https://help.github.com/en/articles/fork-a-repo) about it in the github help pages.
