### ISSUE TITLE
mpris-scrobbler.service isn't being started

### ISSUE THREAD

**Issue by alecvn** [mariusor/mpris-scrobbler#59]
Since I tried to debug #53 by running mpris-scrobbler explicitly with `mpris-scrobbler -vvv` I haven't been able to get mpris-scrobbler running as a service again.

After running `systemctl --user start mpris-scrobbler.service` (which runs without errors), I run `systemctl -l status mpris-scrobbler` and get the output: `Unit mpris-scrobbler.service could not be found.`

**Comment by mariusor** [comment]
I'm not sure why you think that's an issue. By default just compiling the application doesn't set up the systemd service. The only ways that happens would be if:

You installed the package using your distribution's package manager.

You installed the package manually using `ninja install`.

**Comment by alecvn** [comment]
This is a typical case of a XY-problem.  My apologies.  mpris-scrobbler isn't scrobbling for me anymore so I assumed it was because the service isn't showing.
