### ISSUE TITLE
doesn't scrobble (cmus)

### ISSUE THREAD

**Issue by ghost** [mariusor/mpris-scrobbler#65]
I've configured everything correctly and the credentials file has tokens, sesions etc from two services - lastfm, and listenbrainz.

It works with cmus, but not all songs

```
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_playback_status_changed:        yes
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_track_changed:                yes
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_volume_changed:                 no
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_position_changed:                 no
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_playback_status_changed:         no
Aug 31 00:22:32 a mpris-scrobbler[1057]: DEBUG   scrobbler::checking_track_changed:                 no
Aug 31 00:22:32 a mpris-scrobbler[1057]: WARNING events::unable_to_load_scrobble[0x5624738f8c20]
Aug 31 00:23:16 a mpris-scrobbler[1057]: INFO    scrobbler::now_playing: В Руках Времени//Nadezda//В Руках Времени
Aug 31 00:23:17 a mpris-scrobbler[1057]: INFO     api::submitted_to[listenbrainz.org:0]: ok
Aug 31 00:23:17 a mpris-scrobbler[1057]: INFO     api::submitted_to[last.fm:1]: ok

```

**Comment by mariusor** [comment]
For cmus it seems that it sends the signal that the track has changed twice, but with different information each time. Once it tells us that the track has changfed and the second that the playback status has changed (which is not true and non conforming to the spec). 

This means that the logic of the scrobbler can't put the two events together and generate a valid scrobble for them. In my opinion this is a bug in cmus' MPRIS implementation. On a longer term I want to support better heuristics for detecting non-conforming players and do better, but for the moment is not a priority for me. Patches welcome of course.

**Comment by mariusor** [comment]
I am using the latest master (with the commits I did for ticket #66) I can scrobble with cmus. 

Can you try it again for your use case and tell me if it still doesn't scrobble every song? 

Generally the criteria for a valid scrobble are  [here](https://github.com/mariusor/mpris-scrobbler/blob/ceda225d024f6f654d9b085779c90c452969eba0/src/scrobble.h#L304):

* the length is longer than 60 seconds.
* title is a non empty string
* album is a non empty string
* artist is a non empty string 
* track hasn't been scrobbled yet
* the current track has played more than 4 minutes or half the length, whichever comes first.

**Comment by treeshateorcs** [comment]
>the length is longer than 60 seconds.

should be 30 secs
https://www.last.fm/api/scrobbling#when-is-a-scrobble-a-scrobble

**Comment by treeshateorcs** [comment]
scrobbles seem to register on last.fm (but not all, or so it seems), but not on listenbrainz

https://gist.github.com/treeshateorcs/25b7c973b50866b1ce9deaaa7f965133

**Comment by mariusor** [comment]
> should be 30 seconds

Yes [indeed](https://github.com/mariusor/mpris-scrobbler/blob/ceda225d024f6f654d9b085779c90c452969eba0/src/scrobble.h#L11) 

Regarding listenbrainz, I see a lot of `mpris-scrobbler[7951]: INFO     api::submitted_to[listenbrainz.org:0]: ok` 

That means the API returned 200 OK for the submission. You can check that by compiling in debug mode and running the scrobbler with `-vvvv` verbosity, when it also prints the http request/responses.

**Comment by treeshateorcs** [comment]
this is getting weird. track 5 (長い季節) does scrobble, track 4 (春のせい) does not. i don't like track 5 so i had to endure

the above is true for both last.fm and listenbrainz

**Comment by mariusor** [comment]
```WARNING scrobble::valid::title[春のせい]: yes
WARNING scrobble::valid::album[いき]: yes
WARNING scrobble::valid::length[315]: yes
WARNING scrobble::valid::play_time[151.000000:157.500000]: no
```

I think this might be related to scrobbling tracks that have been queued but the scrobble event has been triggered too early for them (151 seconds vs. wanted 157). I think that's a bigger issue to takle, and I'll take a look at it in another weekend.

**Comment by jwflory** [comment]
I wonder if this is fixed in v0.3.91?

**Comment by mariusor** [comment]
Haven't tried cmus in a while. If you do a test, please post an update. :)

**Comment by jwflory** [comment]
v0.3.93 works for me with `cmus` on Fedora 32 :+1:
