### ISSUE TITLE
Scrobble issues with ncspot

### ISSUE THREAD

**Issue by mariusor** [mariusor/mpris-scrobbler#66]
Split ticket from #65 by @treeshateorcs:

I've configured everything correctly and the credentials file has tokens, sesions etc from two services - lastfm, and listenbrainz

and this is what systemctl status tells us

```
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::track_id: spotify:track:4Y2glvLjQGOb4dXnwm1hQf
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::url: spotify:track:4Y2glvLjQGOb4dXnwm1hQf
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::artist: Pendulum
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::album: Immersion
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::album_artist: Pendulum
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::title: Witchcraft
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::track_number:  0
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::art_url: https://i.scdn.co/image/d9e62d4c74905b2071015d6a22299599025035cc
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG     loaded::metadata::timestamp: 1567198334
Aug 30 23:52:14 a mpris-scrobbler[1057]: DEBUG   events::invalid_mpris_properties[0x5624739020d0::0x5624738f5c40]: already loaded

```

I'm playing music with ncspot (spotify client)

**Comment by mariusor** [comment]
Thank you for this report, I didn't know of this player. 

Everything looks fine from the logs, and theoretically it should scrobble, however I can reproduce the issue on my system too. I'll investigate fruther when I get the time.

**Comment by mariusor** [comment]
On a second look I think this is also a problem with the player. 

Somehow it doesn't expose the `/org/mpris/MediaPlayer2/org.freedesktop.DBus.Properties/PropertiesChanged` signal properly. You can verify this by using the Qt Dbus viewer and going to the `org.mpris.MediaPlayer2.ncspot` service.

The scrobbler can load the track, but it doesn't trigger the API submissions, probably because of this missing signal.

I will follow up with a ticket in ncspot and ping you there. Also I will do a double check if the scrobbler can do better on this side.

**Comment by mariusor** [comment]
OK, I think I fixed this (commit ceda225).

In the end the main problem was that the scrobbler wasn't loading a proper track length, which was giving weird behavior (if a track is less than 60 seconds is not valid for now_playing or scrobble submission). 

Please build from master and let me know if it works for you, so I can close the ticket.

PS. Thanx again for bringing ncspot to my attention. :1st_place_medal:

**Comment by treeshateorcs** [comment]
>wasn't loading a proper track length

i think this patch should fix that
https://gist.github.com/treeshateorcs/22697936ea02f710aae7b12920aa9519

**Comment by treeshateorcs** [comment]
oh, i just noticed @hrkfdn has already fixed it

**Comment by mariusor** [comment]
So, does it scrobble fine on your machine?

**Comment by treeshateorcs** [comment]
same issue as with cmus. now playing is being updated, but scrobbles don't register on both services
https://gist.github.com/treeshateorcs/7f7b19d534a516f7c44c64ed7a46c60f

**Comment by mariusor** [comment]
OK, I consider that a different issue and I guess we can track it in #65.

I'll close this.
