### ISSUE TITLE
unable_to_load_scrobble[0x563463707a60] with mpd + mpDris2

### ISSUE THREAD

**Issue by RodrigoLeiteF** [mariusor/mpris-scrobbler#68]
Logs: https://pastebin.com/DdY7ijyX
```
➜  ~ mpd --version
Music Player Daemon 0.21.14 (0.21.14)
➜  ~ mpris-scrobbler --help
MPRIS scrobbler daemon, version 0.3.5-1
➜  ~ mpDris2 --version
mpDris2 version 0.8
```

**Comment by RodrigoLeiteF** [comment]
Oddly enough everything started working after posting this issue. No idea why.

**Comment by mariusor** [comment]
Hi @RodrigoLeiteF , thank you for your interest in mpris-scrobbler.

To go on I will need more information about what is actually happening. Please run the scrobbler as `mpris-scrobbler -vvv`to see more verbose output and use a paste service to post the output somewhere.

Your issue might be the same as #65, but I'll need that debug information to be able to say for sure.

**Comment by RodrigoLeiteF** [comment]
I see. Here's a test run I did, listening to the track "True" by Hannah Diamond in full, then half of "Make Believe" by the same artist.

https://pastebin.com/TB1BfEyw

**Comment by mariusor** [comment]
Honestly I don't know why it didn't scrobble after half of the first track elapsed. The only time it scheduled a scrobble was here:

```DEBUG   events::add_event(0x5578464437a0):scrobble in 118.000 seconds```

But I suspect you killed it before it got a chance to do that.

You might want to leave it running for a couple more songs and see if it manages to scrobble any of them. Usually when a scrobble event is triggered, there's some debug output which says why a track is or isn't scrobbled.

I'll try to reproduce this on my machine with mpd and mpdirs, but I don't have an eta on that.

**Comment by mariusor** [comment]
I believe v0.4.0 fixed this.
