### ISSUE TITLE
mpris-scrobbler and systemd do not work together

### ISSUE THREAD

**Issue by pgueckel** [mariusor/mpris-scrobbler#69]
When mpris-scrobbler is started with:

systemctl --user enable mpris-scrobbler.service (and reboot)
systemctl --user start mpris-scrobbler.service

it does absolutely nothing. It is shown to be running and it can be stopped and restarted, but it never scrobbles.

The only way to get it to do anything is to run it from the command line:

mpris-scrobbler

and to ^c to quit.

**Comment by pgueckel** [comment]
An uneducated guess:

Since systemd is running the program, it would not know about the value of the variable XDG_DATA_HOME, since that value is set in the user .profile file and would likely only become set when the user logs in, but would not likely be available to a system process, even though it is a system-run user process.

Just an idea.

**Comment by mariusor** [comment]
> Since systemd is running the program, it would not know about the value of the variable XDG_DATA_HOME 

If you look at the [service file](https://github.com/mariusor/mpris-scrobbler/blob/master/units/systemd-user.service.in#L8), you can see that it's set to the user's `.local/share` folder.

To debug further what the problems are you need to increase verbosity of the command ran by the service:

```sh
systemctl --user edit --full mpris-scrobbler.service

```

And modify the line `ExecStart` to increase verbosity `ExecStart = /usr/bin/mpris-scrobbler -vvv`

To track what is happening after login you then use `journalctl --user -f -u mpris-scrobbler.service`

You also need to double check if you have two versions of mpris-scrobbler installed: 

```sh
$ which mpris-scrobbler
$ mpris-scrobbler --help 
$ /usr/bin/mpris-scrobbler --help
```

**Comment by pgueckel** [comment]
Yes, I thought of the service file later in the day. I learned something, too: what %h means ;-)

I just ran which and the 2 --help programs. which responded: /usr/bin/mpris-scrobbler and the --help programs responded version (unknown).

I ran the systemctl edit program and modified the ExecStart line. I verified it by displaying in konsole.

I also ran systemctl --user | grep mpris and it displays loaded active running.

I have also switched to rhythmbox, even though I prefer to use qt5/kde5 programs. The problem is that JuK and VLC do not scrobble correctly. They seem to submit only partial data. I checked on listenbrainz and when I use rhythmbox, my listening is shown (I haven't tried often enough to determine whether anything gets skipped yet) and the data that appears in my profile is hyperlinked to the correct tracks in musicbrainz (when I use the other programs, many tracks get skipped and none of them are ever hyperlinked to musicbrainz).

So, now that mpris-scrobbler is running with -vvv, I will listen to some tracks and get some output from journalctl that I will put into a pastebin for you.

**Comment by pgueckel** [comment]
You said: To track what is happening after login.... Do I need to log out and back in? I didn't bother, since I already am logged in and we have just seen that the daemon is loaded active and running.

I started rhythmbox and played some tracks. As you can see here (https://pastebin.com/U09wg7fH), nothing happens.  I don't know what happened to the daemon in the first line (this was during my testing to see if it was active and whether more than one instance was running). What I did was stop it and restart it. This appears to have worked correctly, but it doesn't get anything from rhythmbox at all! Over 4 tracks have played and it registers nothing. But 2 nights ago, I did the same thing by running it from the command line and it spewed out line after line for each and every track (title cover artist and more) and listenbrainz showed the track right away.

I just stopped and restarted mpris-scrobbler while rhythmbox was playing a track and I got another iteration of the following output:

Sep 17 00:00:26 localhost.localdomain mpris-scrobbler[19783]: INFO    main::signal_received: SIGTERM
Sep 17 00:00:26 localhost.localdomain systemd[1307]: Stopping daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services...
Sep 17 00:00:26 localhost.localdomain systemd[1307]: mpris-scrobbler.service: Succeeded.
Sep 17 00:00:26 localhost.localdomain systemd[1307]: Stopped daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services.
Sep 17 00:00:37 localhost.localdomain systemd[1307]: Started daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services.
Sep 17 00:00:37 localhost.localdomain mpris-scrobbler[20238]: DEBUG   main::loading_credentials: ok
Sep 17 00:00:37 localhost.localdomain mpris-scrobbler[20238]: DEBUG   events::loaded_properties: nothing found

It just doesn't do anything when started through systemd.

**Comment by pgueckel** [comment]
I just stopped it and tested with systemctl --user | grep mpris and there is only a blank line of output. It is not running. Then, I started it from the command line. Here is the output that I get while rhythmbox continues to run, uninterrupted and listenbrainz immediately shows both tracks, hyperlinked to musicbrainz:

https://pastebin.com/WmYj0uY3

**Comment by mariusor** [comment]
Based on your pastebin it looks like the tracks should have been submitted to listenbrainz, after 4 minutes of play each time. If that didn't happen, the log doesn't say why, is it possible by any chance that you didn't leave it running long enough?

The tracks get send to the scrobbler services after it played for half it's duration or 4 minutes, whichever comes first (in your case 4 minutes).

**Comment by pgueckel** [comment]
I might have missed the first few seconds of the first track, in yesterday's experiment. The second track played fully. The third track might have gotten chopped off, after the experiment concluded, but I believe not.

To satisfy the experiment, I am running it again. I rebooted; I logged in; I checked that no other instances of scrobbler were running and verified that the user scrobbler is loaded active and running, as per the output of systemctl --user|grep mpris; I started journalctl with the given command; and, finally, I started up rhythmbox and pressed play and have allowed numerous tracks to play from the first second onward to conclusion, without interrupting the playback during or between tracks, allowing the player to do its task for the duration of 3 full tracks, the first being 9:40, the second 7:09 and the third 6:38 long. I terminated the experiment by first quitting journalctl after the third track had fully ended and they played had moved to the start of a fourth track, not part of this experiment, and then quit rhythmbox. This paste shows the results:

https://pastebin.com/jAZDbEeu

As you can see, there is absolutely no scrobbling occurring.

Next, I quit this instance of mpris-scrobbler:

systemctl --user stop mpris-scrobbler.service

and verified that it was stopped with systemctl --user|grep mpris and there was a blank line of output. journalctl responded with:

Sep 17 13:14:44 localhost.localdomain mpris-scrobbler[1379]: INFO    main::signal_received: SIGTERM
Sep 17 13:14:44 localhost.localdomain systemd[1368]: Stopping daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services...
Sep 17 13:14:44 localhost.localdomain systemd[1368]: mpris-scrobbler.service: Succeeded.
Sep 17 13:14:44 localhost.localdomain systemd[1368]: Stopped daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services.

I had left Rhythmbox paused and journalctl running; I ran mpris-scrobbler -vvv before pushing play and allowed it to play 3 full tracks.

Here is the output:

https://pastebin.com/uk3FSNNC

journalctl gave no further output. This verifies that the user instance of mpris-scrobbler is not running or interfering.

As you can verify, I listened to 6 consecutive tracks from the same album in their entirety, with a brief pause about 5 seconds into the 4th track, while I switched from systemd to command line versions of mpris-scrobbler. listenbrainz only shows that I listened to the 4th-6th tracks and believes that I am presently listening to the 7th track on the album, which I, however, stopped before closing all of the programs to conclude the experiment.
