### ISSUE TITLE
Occasional CPU overload, usually when closing player

### ISSUE THREAD

**Issue by jwflory** [mariusor/mpris-scrobbler#71]
I've noticed lately that the mpris-scrobbler process on my system will max out the CPU utilization on my system. My laptop fan or desktop fans will begin spinning up, and looking at `htop` shows the `mpris-scrobbler` process as using 100% of my CPU. Restarting the systemd service is a quick fix and CPU usage goes back to normal, but it still happens about two to three times a day.

I haven't been able to trace the issue down, but I think it usually has to do with closing a music player. The only music players I use are the Spotify desktop client and occasionally [Lollypop](https://wiki.gnome.org/Apps/Lollypop).

Any ideas on how to capture more useful debug info? I'm not an expert on C but happy to do anything I can to debug. I really appreciate this little app, thanks for working on it!

**Comment by mariusor** [comment]
Hi, yes I know of this problem and I get it also when using Spotify as a player. 

I wasn't able to solve the issue so far, but I didn't spend that much time looking into it either. I just restart the scrobbler. :(

I think I have the problem isolated in the loop that reads from dbus the mpris properties and metadata for the current track.

Unfortunatelly my main focus is somewhere else, and I'm not sure when I'll be able to look more into it.

**Comment by jwflory** [comment]
Bummer. Okay, thanks for the update. If you do get time to look into it, I am happy to help test and troubleshoot any way I can. Thanks for your time making this super useful tool.

**Comment by mariusor** [comment]
@jwflory just to keep you updated, I've taken a break from my other projects and started working on mpris-scrobbler. There's a chance this would be fixed in the near future. :)

**Comment by jwflory** [comment]
@mariusor Woohoo awesome! I'll be sure to get any new releases packaged up for Fedora/CentOS/RHEL. :)

**Comment by mariusor** [comment]
Hey, I have progress on this (I hope), can you please give it a try also?

If you can compile latest master, please do so and use it for a while. Let me know if this problem still exists, or if any others crept up in the meanwhile.

There are a lot of changes under the hood, so some things that previously worked might be broken. Apologies if that's the case.

**Comment by jwflory** [comment]
@mariusor I will work on giving it a go and creating a pre-release / beta package in my COPR. Because of nuances in the Fedora package build system, it will make my work easier if you can cut a new git tag first. I can wait to publish in official Fedora repositories until some issues are confirmed and/or closed first.

**Comment by mariusor** [comment]
Hey, in the meantime I had some crashes on my machine, so I'm not fully ready to do a pre-release tag. I'll give it a couple of days for testing on my side and then I'll let you know. Thanx.

**Comment by jwflory** [comment]
@mariusor Thanks. Because of silly constraints in the Fedora build system, and that I am still a RPM scripting novice, make it hard for me to build from untagged commits. A tag (even if just a tag named by the date and not a new version) simplifies my workflow greatly for downstream packaging.

**Comment by mariusor** [comment]
OK, I finally have a candidate ready: [v0.3.90](https://github.com/mariusor/mpris-scrobbler/releases/tag/v0.3.90).

**Comment by jwflory** [comment]
Hi, just confirming I upgraded to v0.3.91 today. Will monitor CPU usage and scrobble reliability more closely for the next few days.

**Comment by jwflory** [comment]
I have been using v0.3.91 for a few hours without any CPU usage spikes and consistent scrobbling. I'm going to close this as fixed for now, and if I notice any change, I will reopen. :slightly_smiling_face: 

Thanks for fixing this, @mariusor! :tada:
