### ISSUE TITLE
Dependencies in Ubuntu seem to be unavailable

### ISSUE THREAD

**Issue by VBtheFirbolg** [mariusor/mpris-scrobbler#82]
I tried installing the dependencies in Ubuntu 20.04, but there were few packages that were missing:
```
sudo apt install libevent-2.1-6 libevent-dev libdbus-1-dev dbus dbus-user-session libcurl4 libcurl4-openssl-dev libjson-c-dev libjson-c3 meson
[sudo] password for ********: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libevent-2.1-6
E: Couldn't find any package by glob 'libevent-2.1-6'
E: Unable to locate package libjson-c3
```
I don't know how to install the daemon now. Is there any workaround?

**Comment by inhji** [comment]
A few packages changed their name in newer versions of Ubuntu, this is the updated list for 20.04:

```
sudo apt install libevent-2.1-7 libevent-dev libdbus-1-dev dbus dbus-user-session libcurl4 libcurl4-openssl-dev libjson-c-dev libjson-c-dev meson m4 scdoc
```

In the future, you can look here (https://packages.ubuntu.com/) for packages in your version of Ubuntu.

**Comment by mariusor** [comment]
Thank you both for the ticket and the solution. :) 
I updated the README with the instructions for Ubuntu 20.04.
