### ISSUE TITLE
Adding a last.fm session fails on Fedora 33

### ISSUE THREAD

**Issue by sillitatti** [mariusor/mpris-scrobbler#83]
I can't get last.fm scrobbling to work on Fedora 33 (installed from the repository). After successfully getting the token, when I do "mpris-scrobbler-signon session lastfm", the credentials file gets overwritten with:

[lastfm]
enabled = false

Before this, there were also crashes

helmi 16 15:44:04 system systemd-coredump[7547]: Process 7471 (mpris-scrobbler) of user 1000 dumped core.
                                                
                                                Stack trace of thread 7471:
                                                #0  0x00007f1c18d739d5 raise (libc.so.6 + 0x3d9d5)
                                                #1  0x00007f1c18d5c8a4 abort (libc.so.6 + 0x268a4)
                                                #2  0x00007f1c18d5c789 __assert_fail_base.cold (libc.so.6 + 0x26789)
                                                #3  0x00007f1c18d6c026 __assert_fail (libc.so.6 + 0x36026)
                                                #4  0x000055d09a9f1443 add_event_now_playing.isra.0 (mpris-scrobbler + 0x7443)
                                                #5  0x000055d09a9f60fb resend_now_playing.part.0 (mpris-scrobbler + 0xc0fb)
                                                #6  0x00007f1c18f36ae2 event_process_active_single_queue (libevent-2.1.so.6 + 0x22ae2)
                                                #7  0x00007f1c18f385d7 event_base_loop (libevent-2.1.so.6 + 0x245d7)
                                                #8  0x000055d09a9eddc4 main (mpris-scrobbler + 0x3dc4)
                                                #9  0x00007f1c18d5e1e2 __libc_start_main (libc.so.6 + 0x281e2)
                                                #10 0x000055d09a9ee1ce _start (mpris-scrobbler + 0x41ce)
                                                
But manually reloading the service seemed to work after this.

**Comment by mariusor** [comment]
Hello @sillitatti, apologies for the long delay in getting back to you.

I think this was discussed in another ticket #79. I'm not sure if @jwflory updated the build scripts to not compile with asserts.

If you can try to compile from source and reproduce, I can take another look, but like this I can't reproduce because I'm not using Fedora.

**Comment by mariusor** [comment]
I'll assume the new versions are fixing this issue, so I'll close the ticket.

If you still encounter errors with version v0.5.0 or higher, @sillitatti feel free to comment back here and I'll reopen the ticket.

**Comment by jwflory** [comment]
I haven't built a new update for the Fedora package yet. I will work on getting an update out soon. I have had some heavy past few weeks at work so my packaging is on a backburner right now…

Alternatively, happy to bring on a co-packager if there is interest in maintaining it with me.

**Comment by gbcox** [comment]
Hey Justin, you can add me as a co-packager.
