### ISSUE TITLE
Can't build on Gentoo

### ISSUE THREAD

**Issue by Phate6660** [mariusor/mpris-scrobbler#84]
Versions:
- Architecture = AMD64
- GCC = 10.3.0-r2

This is the main issue it seems, but the full logs are below:
```
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:26:37: error: ‘%s’ directive output may be truncated writing up to 6662 bytes into a region of size 512 [-Werror=format-truncation=]
   26 | #define TOKENIZED_PID_PATH          "%s/%s%s"
      |                                     ^~~~~~~~~
```

<details>
  <summary>build logs</summary>
<pre>
$ meson build
The Meson build system
Version: 0.58.2
Source dir: /home/valley/Downloads/git/mpris-scrobbler
Build dir: /home/valley/Downloads/git/mpris-scrobbler/build
Build type: native build
Project name: mpris-scrobbler
Project version: undefined
C compiler for the host machine: gcc (gcc 10.3.0 "gcc (Gentoo 10.3.0-r2 p3) 10.3.0")
C linker for the host machine: gcc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.4)
Run-time dependency dbus-1 found: YES 1.12.20
Run-time dependency libcurl found: YES 7.78.0
Run-time dependency libevent_pthreads found: YES 2.1.11-stable
Run-time dependency libevent found: YES 2.1.11-stable
Run-time dependency json-c found: YES 0.15
Configuring credentials_lastfm.h using configuration
Configuring credentials_librefm.h using configuration
Configuring credentials_listenbrainz.h using configuration
Program git found: YES (/usr/bin/git)
Program /usr/lib/python-exec/python3.9/meson found: YES (/usr/lib/python-exec/python3.9/meson)
Program ctags found: YES (/usr/bin/ctags)
Program m4 found: YES (/usr/bin/m4)
Program scdoc found: YES (/usr/bin/scdoc)
Program sh found: YES (/bin/sh)
Build targets in project: 9

Found ninja-1.10.1 at /usr/bin/ninja
$ ninja -C build/
ninja: Entering directory `build/'
[7/10] Compiling C object mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o
FAILED: mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o 
gcc -Impris-scrobbler-signon.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -g '-DAPPLICATION_NAME="mpris-scrobbler"' -DDEBUG -march=ivybridge -O3 -pipe -falign-functions=32 -pthread -Wall -Wextra -fno-omit-frame-pointer -MD -MQ mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -MF mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o.d -o mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -c mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c
In file included from /home/valley/Downloads/git/mpris-scrobbler/build/../src/signon.c:25,
                 from mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c:1:
/home/valley/Downloads/git/mpris-scrobbler/build/../src/signon.c: In function ‘main’:
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:26:37: error: ‘%s’ directive output may be truncated writing up to 6662 bytes into a region of size 512 [-Werror=format-truncation=]
   26 | #define TOKENIZED_PID_PATH          "%s/%s%s"
      |                                     ^~~~~~~~~
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:299:56: note: in expansion of macro ‘TOKENIZED_PID_PATH’
  299 |     return snprintf((char*)config->pid_path, path_len, TOKENIZED_PID_PATH, config->env.xdg_runtime_dir, config->name, PID_SUFFIX);
      |                                                        ^~~~~~~~~~~~~~~~~~
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:26:38: note: format string is defined here
   26 | #define TOKENIZED_PID_PATH          "%s/%s%s"
      |                                      ^~
In file included from /usr/include/stdio.h:866,
                 from /usr/include/curl/curl.h:49,
                 from /home/valley/Downloads/git/mpris-scrobbler/build/../src/signon.c:6,
                 from mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c:1:
/usr/include/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 6 and 12817 bytes into a destination of size 512
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |        __glibc_objsize (__s), __fmt,
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |        __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[8/10] Compiling C object mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o
FAILED: mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o 
gcc -Impris-scrobbler.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -g '-DAPPLICATION_NAME="mpris-scrobbler"' -DDEBUG -march=ivybridge -O3 -pipe -falign-functions=32 -pthread -Wall -Wextra -fno-omit-frame-pointer -MD -MQ mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -MF mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o.d -o mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -c mpris-scrobbler.p/mpris-scrobbler-unity0.c
In file included from /home/valley/Downloads/git/mpris-scrobbler/build/../src/daemon.c:19,
                 from mpris-scrobbler.p/mpris-scrobbler-unity0.c:1:
/home/valley/Downloads/git/mpris-scrobbler/build/../src/daemon.c: In function ‘main’:
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:26:37: error: ‘%s’ directive output may be truncated writing up to 6662 bytes into a region of size 512 [-Werror=format-truncation=]
   26 | #define TOKENIZED_PID_PATH          "%s/%s%s"
      |                                     ^~~~~~~~~
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:299:56: note: in expansion of macro ‘TOKENIZED_PID_PATH’
  299 |     return snprintf((char*)config->pid_path, path_len, TOKENIZED_PID_PATH, config->env.xdg_runtime_dir, config->name, PID_SUFFIX);
      |                                                        ^~~~~~~~~~~~~~~~~~
/home/valley/Downloads/git/mpris-scrobbler/build/../src/configuration.h:26:38: note: format string is defined here
   26 | #define TOKENIZED_PID_PATH          "%s/%s%s"
      |                                      ^~
In file included from /usr/include/stdio.h:866,
                 from /usr/include/curl/curl.h:49,
                 from /home/valley/Downloads/git/mpris-scrobbler/build/../src/daemon.c:5,
                 from mpris-scrobbler.p/mpris-scrobbler-unity0.c:1:
/usr/include/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 6 and 12817 bytes into a destination of size 512
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |        __glibc_objsize (__s), __fmt,
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |        __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
</pre>
</details>

**Comment by mariusor** [comment]
@Phate6660 apologies for the long delay in getting back to you.

Unfortunately I am not patient enough to track down all the gcc truncation errors (currently there are over 350 of them). You can update the build script to set `-Werror=format-truncation=0`.

Patches welcome to track them down of course. :D
