### ISSUE TITLE
Crash during configuration

### ISSUE THREAD

**Issue by Trez-zerT** [mariusor/mpris-scrobbler#87]
I just installed 0.4.99-1 on Manjaro and consistently receive the following error when trying to login:

mpris-scrobbler-signon token lastfm                                                                                                                                                                                       
WARNING main::load_credentials: no credentials were loaded
zsh: segmentation fault (core dumped)  mpris-scrobbler-signon token lastfm

xdg-open seems to work fine on its own, so I'm not sure how to progress from here.

**Comment by mariusor** [comment]
Hi, thank you for the report.

 I can reproduce this on my machine. I'll try to come up with a fix soon(ish).

**Comment by mariusor** [comment]
OK, I have fixed the problems with the signon helper. I'll try to get v0.5 out the door soon.

In the meantime you can try installing the package form source. :)

Here's a PKGBUILD file for the -git version:

```
# Maintainer: Marius Orcsik <marius@littr.me>
pkgname=mpris-scrobbler-git
pkgver=v0.4.99.r17.db560ba
pkgrel=1
pkgdesc="Minimalistic user daemon which submits the currently playing song to libre.fm and compatible services."
arch=('x86' 'x86_64')
url="https://github.com/mariusor/mpris-scrobbler"
license=('MIT')
makedepends=('git' 'dbus>=1.9' 'libevent' 'curl' 'json-c' 'meson' 'ninja' 'scdoc')
depends=('dbus>=1.9' 'libevent' 'curl' 'json-c')
optdepends=('scdoc')
conflicts=("${pkgname%-git}")
source=("${pkgname%-git}::git+https://github.com/mariusor/${pkgname%-git}")
sha256sums=('SKIP')
pkgver() {
	cd "$srcdir/${pkgname%-git}"
	printf "%s" "$(git describe --long | sed 's/\([^-]*-\)g/r\1/;s/-/./g')"
}

build() {
	cd "${pkgname%-git}"
	rm -rf build/
	meson -Dbuildtype=release -Dversion="${pkgver}-${pkgrel}" --prefix=/usr --unity on build/
	ninja --verbose -C build/
}

package() {
	cd "${pkgname%-git}"
	mkdir -p "$pkgdir"
	DESTDIR="$pkgdir" ninja -C build/ install
}
```

**Comment by mariusor** [comment]
Let me know if this fixes your issue.

**Comment by Trez-zerT** [comment]
Well, I got a bit further:

WARNING main::load_credentials: no credentials were loaded
Maximum number of clients reachedqt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

/usr/bin/xdg-open: line 613: 2752494 Aborted                 (core dumped) kde-open${KDE_SESSION_VERSION} "$1"

I guess I need to figure out xdg-open now.

**Comment by mariusor** [comment]
The error makes it look like you're running a Wayland compositor without X enabled. Maybe you need to specify `QT_QPA_PLATFOR=wayland mpris-scrobbler-signon token lastfm` which should pass the environment variable to the kde-open binary.

Can you test if kde-open works from the same terminal ? Something like `kde-open https://fsf.org` I suspect if you can make this work, the signon will go through. Fingers crossed.

**Comment by Trez-zerT** [comment]
YES! Thank you. This launched the website and let me authorize.
