### ISSUE TITLE
Scrobbling fails with version 0.4.99 and 0.5.0 curl error timeout

### ISSUE THREAD

**Issue by gbcox** [mariusor/mpris-scrobbler#89]
When testing with .5 nothing appears to make it to Listenbrainz.  I tested with another program and it works so doesn't appear to be an issue with Listenbrainz.  Also, as an FYI... with the upgrade to Fedora 36 I had to add -Wno-address to get it to build.  So the overrides are now:  -Dc_args="-fPIE -Wno-address -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation"

I was receiving the following complile errors (for the scrobbling errors, go to the end of this message):
FAILED: mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o 
gcc -Impris-scrobbler.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -Werror=format-truncation=0 -Wno-stringop-overflow -fPIE -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -MD -MQ mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -MF mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o.d -o mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -c mpris-scrobbler.p/mpris-scrobbler-unity0.c
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:11,
                 from mpris-scrobbler.p/mpris-scrobbler-unity0.c:1:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h: In function ‘array_log_with_label’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h:138:20: error: the comparison will always evaluate as ‘false’ for the pointer operand in ‘arr + (sizetype)((long unsigned int)i * 512)’ must not be NULL [-Werror=address]
  138 |         if (arr[i] == NULL || strlen(arr[i]) == 0) {
      |                    ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h: In function ‘arguments_clean’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h:210:14: error: the comparison will always evaluate as ‘false’ for the address of ‘pid_path’ will never be NULL [-Werror=address]
  210 |     if (NULL == args->pid_path) { string_free(args->pid_path); }
      |              ^~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:10:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:295:10: note: ‘pid_path’ declared here
  295 |     char pid_path[MAX_PROPERTY_LENGTH + 1];
      |          ^~~~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:79,
                 from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:12:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_get_session’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h:395:14: error: the comparison will always evaluate as ‘true’ for the address of ‘sig_base’ will never be NULL [-Werror=address]
  395 |     if (NULL != sig_base) { grrrs_free(sig_base); }
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h:350:10: note: ‘sig_base’ declared here
  350 |     char sig_base[MAX_BODY_SIZE] = {0};
      |          ^~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h: In function ‘credentials_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:466:46: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  466 |     return (NULL != c && c->enabled && (NULL != c->session_key));
      |                                              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobbler.h:9,
                 from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:14:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/curl.h: In function ‘http_response_write_headers’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/curl.h:291:14: error: the comparison will always evaluate as ‘false’ for the address of ‘name’ will never be NULL [-Werror=address]
  291 |     if (NULL == h->name  || strlen(h->name) == 0) { goto _err_exit; }
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:44:10: note: ‘name’ declared here
   44 |     char name[MAX_HEADER_NAME_LENGTH];
      |          ^~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:15:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘print_scrobble_valid_check’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:346:14: error: the comparison will always evaluate as ‘true’ for the address of ‘artist’ will never be NULL [-Werror=address]
  346 |     if (NULL != s->artist && NULL != s->artist[0]) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:346:35: error: the comparison will always evaluate as ‘true’ for the address of ‘artist’ will never be NULL [-Werror=address]
  346 |     if (NULL != s->artist && NULL != s->artist[0]) {
      |                                   ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘scrobble_is_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:361:45: error: the comparison will always evaluate as ‘false’ for the address of ‘artist’ will never be NULL [-Werror=address]
  361 |     if (array_count(s->artist) == 0 || NULL == s->artist[0]) { return false; }
      |                                             ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘now_playing_is_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:389:45: error: the comparison will always evaluate as ‘false’ for the address of ‘artist’ will never be NULL [-Werror=address]
  389 |     if (array_count(m->artist) == 0 || NULL == m->artist[0]) { return false; }
      |                                             ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/daemon.c:19:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘get_ini_from_credentials’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:96:18: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
   96 |         if (NULL != current->token && strlen(current->token) > 0) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:100:18: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  100 |         if (NULL != current->session_key && strlen(current->session_key) > 0) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘api_credentials_disable’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:148:14: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
  148 |     if (NULL != credentials->token) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:151:14: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  151 |     if (NULL != credentials->session_key) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘print_application_config’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:555:18: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
  555 |         if (NULL != cur->token) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:558:18: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  558 |         if (NULL != cur->session_key) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
cc1: all warnings being treated as errors
[8/10] gcc -Impris-scrobbler-signon.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -Werror=format-truncation=0 -Wno-stringop-overflow -fPIE -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -D_POSIX_C_SOURCE=200809L -MD -MQ mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -MF mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o.d -o mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -c mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c
FAILED: mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o 
gcc -Impris-scrobbler-signon.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -Werror=format-truncation=0 -Wno-stringop-overflow -fPIE -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -D_POSIX_C_SOURCE=200809L -MD -MQ mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -MF mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o.d -o mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -c mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:16,
                 from mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c:1:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h: In function ‘array_log_with_label’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h:138:20: error: the comparison will always evaluate as ‘false’ for the pointer operand in ‘arr + (sizetype)((long unsigned int)i * 512)’ must not be NULL [-Werror=address]
  138 |         if (arr[i] == NULL || strlen(arr[i]) == 0) {
      |                    ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h: In function ‘arguments_clean’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/utils.h:210:14: error: the comparison will always evaluate as ‘false’ for the address of ‘pid_path’ will never be NULL [-Werror=address]
  210 |     if (NULL == args->pid_path) { string_free(args->pid_path); }
      |              ^~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:14:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:295:10: note: ‘pid_path’ declared here
  295 |     char pid_path[MAX_PROPERTY_LENGTH + 1];
      |          ^~~~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:79,
                 from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:17:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_get_session’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h:395:14: error: the comparison will always evaluate as ‘true’ for the address of ‘sig_base’ will never be NULL [-Werror=address]
  395 |     if (NULL != sig_base) { grrrs_free(sig_base); }
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/audioscrobbler_api.h:350:10: note: ‘sig_base’ declared here
  350 |     char sig_base[MAX_BODY_SIZE] = {0};
      |          ^~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h: In function ‘credentials_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:466:46: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  466 |     return (NULL != c && c->enabled && (NULL != c->session_key));
      |                                              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobbler.h:9,
                 from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:19:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/curl.h: In function ‘http_response_write_headers’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/curl.h:291:14: error: the comparison will always evaluate as ‘false’ for the address of ‘name’ will never be NULL [-Werror=address]
  291 |     if (NULL == h->name  || strlen(h->name) == 0) { goto _err_exit; }
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/api.h:44:10: note: ‘name’ declared here
   44 |     char name[MAX_HEADER_NAME_LENGTH];
      |          ^~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:20:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘print_scrobble_valid_check’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:346:14: error: the comparison will always evaluate as ‘true’ for the address of ‘artist’ will never be NULL [-Werror=address]
  346 |     if (NULL != s->artist && NULL != s->artist[0]) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:346:35: error: the comparison will always evaluate as ‘true’ for the address of ‘artist’ will never be NULL [-Werror=address]
  346 |     if (NULL != s->artist && NULL != s->artist[0]) {
      |                                   ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘scrobble_is_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:361:45: error: the comparison will always evaluate as ‘false’ for the address of ‘artist’ will never be NULL [-Werror=address]
  361 |     if (array_count(s->artist) == 0 || NULL == s->artist[0]) { return false; }
      |                                             ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h: In function ‘now_playing_is_valid’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/scrobble.h:389:45: error: the comparison will always evaluate as ‘false’ for the address of ‘artist’ will never be NULL [-Werror=address]
  389 |     if (array_count(m->artist) == 0 || NULL == m->artist[0]) { return false; }
      |                                             ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:156:10: note: ‘artist’ declared here
  156 |     char artist[MAX_PROPERTY_COUNT][MAX_PROPERTY_LENGTH];
      |          ^~~~~~
In file included from /home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:24:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘get_ini_from_credentials’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:96:18: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
   96 |         if (NULL != current->token && strlen(current->token) > 0) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:100:18: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  100 |         if (NULL != current->session_key && strlen(current->session_key) > 0) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘api_credentials_disable’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:148:14: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
  148 |     if (NULL != credentials->token) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:151:14: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  151 |     if (NULL != credentials->session_key) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h: In function ‘print_application_config’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:555:18: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
  555 |         if (NULL != cur->token) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];
      |                ^~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/configuration.h:558:18: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  558 |         if (NULL != cur->session_key) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c: In function ‘get_session’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:107:18: error: the comparison will always evaluate as ‘true’ for the address of ‘session_key’ will never be NULL [-Werror=address]
  107 |         if (NULL != creds->session_key) {
      |                  ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:67:16: note: ‘session_key’ declared here
   67 |     const char session_key[MAX_SECRET_LENGTH + 1];
      |                ^~~~~~~~~~~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c: In function ‘get_token’:
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/signon.c:149:14: error: the comparison will always evaluate as ‘true’ for the address of ‘token’ will never be NULL [-Werror=address]
  149 |     if (NULL != creds->token && strlen(creds->token) > 0) {
      |              ^~
/home/gbcox/rpmbuild/BUILD/mpris-scrobbler-0.5.0/redhat-linux-build/../src/structs.h:66:16: note: ‘token’ declared here
   66 |     const char token[MAX_SECRET_LENGTH + 1];

Here is what I get when I play music with elisa.  I also tested with QMMP and received the same thing:

● mpris-scrobbler.service - daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services
     Loaded: loaded (/usr/lib/systemd/user/mpris-scrobbler.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-05-10 12:17:08 -03; 1min 20s ago
       Docs: man:mpris-scrobbler
   Main PID: 476187 (mpris-scrobbler)
      Tasks: 1 (limit: 8821)
     Memory: 7.1M
        CPU: 776ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/mpris-scrobbler.service
             └─476187 /usr/bin/mpris-scrobbler -vvvvvv

May 10 12:18:03 elysium mpris-scrobbler[476187]: DEBUG   events::add_event:now_playing[Elisa] in 0.00s, elapsed 6.00s
May 10 12:18:03 elysium mpris-scrobbler[476187]: DEBUG   events::add_event:queue[Elisa] in 109.00s
May 10 12:18:26 elysium mpris-scrobbler[476187]: WARNING curl::transfer::done[0]: https://api.listenbrainz.org/1/submit-listens => (28) SSL connection timeout
May 10 12:18:26 elysium mpris-scrobbler[476187]: INFO     api::submitted_to[listenbrainz.org]: nok
May 10 12:18:26 elysium mpris-scrobbler[476187]: DEBUG   curl::retrying[3]: in 5.00s
May 10 12:18:26 elysium mpris-scrobbler[476187]: WARNING curl::transfer::done[1]: https://api.listenbrainz.org/1/submit-listens => (28) SSL connection timeout
May 10 12:18:26 elysium mpris-scrobbler[476187]: INFO     api::submitted_to[listenbrainz.org]: nok
May 10 12:18:26 elysium mpris-scrobbler[476187]: DEBUG   curl::retrying[1]: in 3.00s
May 10 12:18:26 elysium mpris-scrobbler[476187]: INFO    scrobbler::now_playing[Elisa]: Take On Me//A-Ha//Hunting High And Low
May 10 12:18:26 elysium mpris-scrobbler[476187]: DEBUG   events::add_event:now_playing[Elisa] in 65.00s, elapsed 6.00s

I'm also seeing this error upon occasion.  I need to restart the daemon to clear:

● mpris-scrobbler.service - daemon to scrobble tracks loaded from the MPRIS DBus interface to compatible services
     Loaded: loaded (/usr/lib/systemd/user/mpris-scrobbler.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-05-10 17:57:40 -03; 16h ago
       Docs: man:mpris-scrobbler
   Main PID: 34694 (mpris-scrobbler)
      Tasks: 1 (limit: 8821)
     Memory: 7.6M
        CPU: 14.334s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/mpris-scrobbler.service
             └─34694 /usr/bin/mpris-scrobbler -vvvvvv

May 11 10:51:35 elysium mpris-scrobbler[34694]: DEBUG   changed::track:               yes
May 11 10:51:35 elysium mpris-scrobbler[34694]: DEBUG   changed::volume:               no
May 11 10:51:35 elysium mpris-scrobbler[34694]: DEBUG   changed::position:             no
May 11 10:51:35 elysium mpris-scrobbler[34694]: DEBUG   changed::playback_status:      no
May 11 10:51:35 elysium mpris-scrobbler[34694]: DEBUG   changed::track:               yes
May 11 10:51:35 elysium mpris-scrobbler[34694]: WARNING events::invalid_scrobble
May 11 10:51:35 elysium mpris-scrobbler[34694]: INFO    mpris_player::closed[1]: org.mpris.MediaPlayer2.firefox.instance2909:1.138
May 11 10:55:47 elysium mpris-scrobbler[34694]: ERROR     mpris::failed_to_load_player_name: This message iterator must have variant type
May 11 10:55:47 elysium mpris-scrobbler[34694]: INFO    mpris_player::opened[1]: org.mpris.MediaPlayer2.elisa:1.15749
May 11 10:55:47 elysium mpris-scrobbler[34694]: WARNING mpris_player::unable to load properties from message

**Comment by mariusor** [comment]
Hey @gbcox, I'm late as always to looking at the issues. :)

I'll take a look at the timeouts and increase them, but no promises when I'll have a version with a fix. As you are already compiling from source you could submit a PR with a value that works for you [here](https://github.com/mariusor/mpris-scrobbler/blob/668ce26b0c6238746089d8aafe8e47cabb4b177d/src/curl.h#L372)

**Comment by gbcox** [comment]
Resolved with patch.
