### ISSUE TITLE
mpris-scrobbler: __strlen_avx2(): mpris-scrobbler killed by SIGSEGV

### ISSUE THREAD

**Issue by gbcox** [mariusor/mpris-scrobbler#96]
Issue opened here: https://bugzilla.redhat.com/show_bug.cgi?id=2248912

Additional attachments can be found in the Fedora Bug.  If you have problems accessing or would like them attached here, please LMK.

Version-Release number of selected component:
mpris-scrobbler-0.5.0-5.fc39

Additional info:
reporter:       libreport-2.17.11
type:           CCpp
reason:         mpris-scrobbler killed by SIGSEGV
journald_cursor: s=57964e5dcb584edcaff7ae6f94fdeb50;i=1e2d0;b=77eee47795614f87bba411c2051e6280;m=e9174416;t=609badc37e7ff;x=dd666725065b427e
executable:     /usr/bin/mpris-scrobbler
cmdline:        /usr/bin/mpris-scrobbler -vv
cgroup:         0::/user.slice/user-1000.slice/[user@1000.service](mailto:user@1000.service)/app.slice/mpris-scrobbler.service
rootdir:        /
uid:            1000
kernel:         6.5.10-300.fc39.x86_64
package:        mpris-scrobbler-0.5.0-5.fc39
runlevel:       N 5
backtrace_rating: 4
crash_function: __strlen_avx2

Truncated backtrace:
Thread no. 1 (10 frames)
 #0 __strlen_avx2 at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
 #1 audioscrobbler_api_build_request_scrobble at /usr/src/debug/mpris-scrobbler-0.5.0-5.fc39.x86_64/redhat-linux-build/../src/audioscrobbler_api.h:572
 #3 api_build_request_scrobble at /usr/src/debug/mpris-scrobbler-0.5.0-5.fc39.x86_64/redhat-linux-build/../src/api.h:615
 #4 api_request_do at /usr/src/debug/mpris-scrobbler-0.5.0-5.fc39.x86_64/redhat-linux-build/../src/scrobbler.h:196
 #5 scrobbles_consume_queue at /usr/src/debug/mpris-scrobbler-0.5.0-5.fc39.x86_64/redhat-linux-build/../src/scrobble.h:527
 #6 queue at /usr/src/debug/mpris-scrobbler-0.5.0-5.fc39.x86_64/redhat-linux-build/../src/sevents.h:203
 #7 event_process_active_single_queue at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1691
 #8 event_process_active at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1783
 #9 event_base_loop at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:2006
 #10 event_base_dispatch at /usr/src/debug/libevent-2.1.12-9.fc39.x86_64/event.c:1817

**Comment by mariusor** [comment]
Thank you @gbcox, I'll have a look.

**Comment by mariusor** [comment]
Sadly this issue has not occurred on any of the machines I run the scrobbler on, so it hasn't been possible to explicitly fix. Hopefully version v0.5.2 which had as a focus a lot of `-Wpedantic` and `-Wextra` warnings has caught this and it's fixed, but I won't get my hopes up. :)

**Comment by gbcox** [comment]
Appears to be fixed by v0.5.2.  Will close for now and open a new bug and reference this one if it re-occurs.  Thanks!
