### ISSUE TITLE
Compile Failure, Errors 0.5.1

### ISSUE THREAD

**Issue by gbcox** [mariusor/mpris-scrobbler#97]
Hello, thanks for the new release.  I receive the following warnings/errors when I compile.  I can bypass and successfully
compile by adding -Wno-error, but wanted to make sure you are aware and this is what you intended.  LMK.
Thanks!

FAILED: mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o 
gcc -Impris-scrobbler.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -g -fPIE -Wno-address -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -MD -MQ mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -MF mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o.d -o mpris-scrobbler.p/meson-generated_mpris-scrobbler-unity0.c.o -c mpris-scrobbler.p/mpris-scrobbler-unity0.c
In file included from /home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/api.h:79,
                 from /home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/daemon.c:12,
                 from mpris-scrobbler.p/mpris-scrobbler-unity0.c:1:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_scrobble.part.0’:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:669:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  669 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:669:5: note: length computed here
  669 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:673:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  673 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:673:5: note: length computed here
  673 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_now_playing.part.0.isra’:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:464:9: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  464 |         strncat(full_artist, artist, artist_len + 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:456:29: note: length computed here
  456 |         size_t artist_len = strlen(artist);
      |                             ^~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:509:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  509 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:509:5: note: length computed here
  509 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:513:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  513 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:513:5: note: length computed here
  513 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[8/10] gcc -Impris-scrobbler-signon.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -g -fPIE -Wno-address -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -D_POSIX_C_SOURCE=200809L -MD -MQ mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -MF mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o.d -o mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -c mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c
FAILED: mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o 
gcc -Impris-scrobbler-signon.p -I. -I.. -I../src -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/json-c -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c11 -O3 -g -fPIE -Wno-address -Wno-stringop-truncation -Wno-unused-parameter -Wno-free-nonheap-object -Wno-format-truncation '-DAPPLICATION_NAME="mpris-scrobbler"' -D_POSIX_C_SOURCE=200809L -MD -MQ mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -MF mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o.d -o mpris-scrobbler-signon.p/meson-generated_mpris-scrobbler-signon-unity0.c.o -c mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c
In file included from /home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/api.h:79,
                 from /home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/signon.c:17,
                 from mpris-scrobbler-signon.p/mpris-scrobbler-signon-unity0.c:1:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_scrobble.part.0’:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:669:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  669 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:669:5: note: length computed here
  669 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:673:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  673 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:673:5: note: length computed here
  673 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h: In function ‘audioscrobbler_api_build_request_now_playing.part.0.isra’:
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:464:9: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  464 |         strncat(full_artist, artist, artist_len + 1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:456:29: note: length computed here
  456 |         size_t artist_len = strlen(artist);
      |                             ^~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:509:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  509 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:509:5: note: length computed here
  509 |     strncat(body, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:513:5: error: ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  513 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build/../src/audioscrobbler_api.h:513:5: note: length computed here
  513 |     strncat(sig_base, sk, strlen(sk));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/gbcox/fedpkg/mpris-scrobbler/mpris-scrobbler-0.5.1/redhat-linux-build -j 8 -v
error: Bad exit status from /var/tmp/rpm-tmp.bQnjrt (%build)

**Comment by mariusor** [comment]
Hey @gbcox, thank you for the ticket, I pushed a version [v0.5.2](https://github.com/mariusor/mpris-scrobbler/releases/tag/v0.5.2) of the scrobbler that, I hope, has fixed most of the stringop-overflow warnings. 

Please give it a try and let me know it it works for you. If it still doesn't, the solution would be to add `-Wno-error=stringop-overflow` to the CFLAGS environment variable. See this example in the Archlinux [PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpris-scrobbler#n19).

Also, I think I mentioned it before, but I don't really keep track of issues here so that's why it takes a long time before I reply. 


If you'd like me to react faster to the issues please write to the mailing list mentioned in the [README](https://github.com/mariusor/mpris-scrobbler?tab=readme-ov-file#resources). It should be enough to just send the link to the github issue.

**Comment by gbcox** [comment]
Thanks!  Much appreciated.  v0.5.2 eliminated all the errors.  Closing this as resolved.
